version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: "no"
    container_name: dbjkb
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - jkbnetwork

  wordpress:
    depends_on:
      - db
    image: wordpress:beta-php7.4-apache
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: "no"
    networks:
      - jkbnetwork
    volumes:
      -  ./htdocs:/var/www/html
    container_name: wordpressjkb
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
    networks:
      - jkbnetwork

  mailhog:
    image: mailhog/mailhog
    ports: 
      - ${MAILHOG_SMTP_PORT}:1025 # smtp server
      - ${MAILHOG_WEB_PORT}:8025 # web ui
    networks:
      - jkbnetwork

  node:
    image: node:16
    volumes:
      - ./htdocs:/var/www/html
    command: npm run watch
    working_dir: /var/www/html/wp-content/themes/jkb-child/
    networks:
      - jkbnetwork

networks:
  jkbnetwork:
volumes:
  db_data: {}
